language: python 
python: 
  - '3.5'
before_script:
  - pipenv install

branches:
  only:
    - staging

env: DJANGO_SETTING_MODULE="purbeurre.settings.travis"

services:
  - postgresql

scipt:
  - ./manage.py test